### ISSUE TITLE
Disable chrome notifications?

### ISSUE THREAD

**Issue by PrairieSailor** [hpsu/nzbget-chrome#77]
I accidently enabled notifications and don't seem to know how to DISABLE them now.

**Comment by hpsu** [comment]
Uncheck the "Enable notifications" option.

(Right click the nzbget-chrome icon and pick options)

**Comment by PrairieSailor** [comment]
> Uncheck the "Enable notifications" option.
> 
> (Right click the nzbget-chrome icon and pick options)

Sorry there is no "Enable Notifications" option.  I only get the following:

Protcol
Host
Port
Username
Password
Path 
History

**Comment by hpsu** [comment]
Sorry, you are probably using the version from chrome webstore that I can no longer update due to reasons outlined [here](https://github.com/hpsu/nzbget-chrome/issues/76#issuecomment-610577110)

A workaround if you can't use latest code from GIT:
1. Goto chrome:/extensions
2. Temporarily enable Developer mode
3. Click details on nzbget-chrome
4. Click background page under Inspect views
5. Select the Application tab, expand Local storage and select the extension
6. Edit opt_notifications to say *false* instead of true

**Comment by PrairieSailor** [comment]
Thanks.  I installed the dev version from git and see the option.  Thanks
